application: spend-in-car
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /.*
  script: index.application
  login: required

libraries:
- name: webapp2
  version: 2.5.1
- name: jinja2
  version: 2.6